// masterdata/world_flags.json → WorldFlags.g.cs 소스 생성기. docs/01 §1.
//
// RoslynCodeTaskFactory 로 실행되는 MSBuild 인라인 태스크다 (Npc.Core.csproj 의 UsingTask 참조).
// 이 파일은 Npc.Core 어셈블리에 컴파일되지 않는다 — csproj 에서 Compile Remove 로 뺀다.
//
// 왜 손으로 쓴 enum 을 두지 않는가:
//   world_flags.json 과 enum 이 어긋나는 순간 플랜 검증이 조용히 틀린 답을 낸다.
//   bit 번호가 하나만 밀려도 프리베이크된 플랜 2,880개가 통째로 무효가 된다.
//
// RoslynCodeTaskFactory 는 netstandard2.0 표면만 참조할 수 있어 System.Text.Json 을 쓸 수 없다.
// world_flags.json 은 우리가 형식을 통제하는 파일이므로 정규식으로 읽는다.
// 형식 자체의 무결성(개수·중복·예약 구간)은 WorldFlagsDataTests 와 MasterDataValidator 가 본다.

#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Build.Framework;

public sealed class WorldFlagsGenerator : Microsoft.Build.Utilities.Task
{
    /// <summary>masterdata/world_flags.json 경로.</summary>
    [Required]
    public string InputPath { get; set; } = string.Empty;

    /// <summary>생성할 WorldFlags.g.cs 경로 (obj/ 아래).</summary>
    [Required]
    public string OutputPath { get; set; } = string.Empty;

    public override bool Execute()
    {
        if (!File.Exists(InputPath))
        {
            Log.LogError("world_flags.json 을 찾지 못했다: {0}", InputPath);
            return false;
        }

        string json = File.ReadAllText(InputPath, Encoding.UTF8);

        // "flags" 배열만 읽는다. reserved_bits 는 숫자만 있어 이 패턴에 걸리지 않는다.
        var entries = new List<KeyValuePair<int, string>>();
        var seenBits = new HashSet<int>();
        var seenIds = new HashSet<string>(StringComparer.Ordinal);

        Regex pattern = new Regex(
            "\\{\\s*\"bit\"\\s*:\\s*(?<bit>\\d+)\\s*,\\s*\"id\"\\s*:\\s*\"(?<id>[A-Za-z][A-Za-z0-9_]*)\"",
            RegexOptions.CultureInvariant);

        foreach (Match m in pattern.Matches(json))
        {
            int bit = int.Parse(m.Groups["bit"].Value, CultureInfo.InvariantCulture);
            string id = m.Groups["id"].Value;

            if (bit < 0 || bit > 63)
            {
                Log.LogError("world_flags.json: bit {0} 이 0~63 범위를 벗어난다 ({1})", bit, id);
                return false;
            }

            if (!seenBits.Add(bit))
            {
                Log.LogError("world_flags.json: bit {0} 이 중복이다 ({1})", bit, id);
                return false;
            }

            if (!seenIds.Add(id))
            {
                Log.LogError("world_flags.json: id {0} 이 중복이다", id);
                return false;
            }

            entries.Add(new KeyValuePair<int, string>(bit, id));
        }

        if (entries.Count == 0)
        {
            Log.LogError("world_flags.json 에서 플래그를 하나도 읽지 못했다. 형식이 바뀌었는가?");
            return false;
        }

        entries.Sort((a, b) => a.Key.CompareTo(b.Key));

        string generated = Render(entries);

        // 내용이 같으면 쓰지 않는다 — 타임스탬프가 바뀌면 매번 재컴파일한다.
        if (File.Exists(OutputPath) && File.ReadAllText(OutputPath, Encoding.UTF8) == generated)
        {
            return true;
        }

        string? dir = Path.GetDirectoryName(OutputPath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }

        // BOM 을 붙인다. 한국어 주석이 들어가는데 BOM 이 없으면 컴파일러가
        // 시스템 기본 코드페이지로 읽을 여지가 남는다.
        File.WriteAllText(OutputPath, generated, new UTF8Encoding(true));
        Log.LogMessage(MessageImportance.Normal, "WorldFlags.g.cs 생성: 플래그 {0}개", entries.Count);
        return true;
    }

    private static string Render(List<KeyValuePair<int, string>> entries)
    {
        var sb = new StringBuilder();

        sb.Append("// <auto-generated />\n");
        sb.Append("// masterdata/world_flags.json 에서 생성된다. 직접 편집하지 않는다.\n");
        sb.Append("// 생성기: src/Npc.Core/Generators/WorldFlagsGenerator.cs\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("namespace Npc.Core;\n\n");

        sb.Append("/// <summary>\n");
        sb.Append("/// 월드 상태 비트 플래그. docs/01 §1.\n");
        sb.Append("/// 플랜의 전제조건·효과, 인지 스캔의 이탈 판정이 전부 이 64비트 위에서 돈다.\n");
        sb.Append("/// </summary>\n");
        sb.Append("[System.Flags]\n");
        sb.Append("public enum WorldFlags : ulong\n{\n");
        sb.Append("    None = 0UL,\n");
        foreach (KeyValuePair<int, string> e in entries)
        {
            sb.Append("    ").Append(e.Value).Append(" = 1UL << ")
              .Append(e.Key.ToString(CultureInfo.InvariantCulture)).Append(",\n");
        }

        sb.Append("}\n\n");

        sb.Append("/// <summary>\n");
        sb.Append("/// WorldFlags 의 이름 표. 마스터데이터의 flag id 문자열을 비트로 바꾸고,\n");
        sb.Append("/// 검증기 3단의 Explain() 이 비트마스크 대신 이름을 내보내게 한다 (docs/03 §3).\n");
        sb.Append("/// </summary>\n");
        sb.Append("public static class WorldFlagTable\n{\n");

        sb.Append("    /// <summary>정의된 플래그 개수.</summary>\n");
        sb.Append("    public const int Count = ")
          .Append(entries.Count.ToString(CultureInfo.InvariantCulture)).Append(";\n\n");

        sb.Append("    /// <summary>정의된 모든 비트의 OR. 미정의 비트 검출에 쓴다.</summary>\n");
        sb.Append("    public const WorldFlags All = (WorldFlags)0x");
        ulong all = 0;
        foreach (KeyValuePair<int, string> e in entries)
        {
            all |= 1UL << e.Key;
        }

        sb.Append(all.ToString("X16", CultureInfo.InvariantCulture)).Append("UL;\n\n");

        sb.Append("    /// <summary>bit 번호 오름차순의 플래그 이름.</summary>\n");
        sb.Append("    public static readonly string[] Names =\n    [\n");
        foreach (KeyValuePair<int, string> e in entries)
        {
            sb.Append("        \"").Append(e.Value).Append("\",\n");
        }

        sb.Append("    ];\n\n");

        sb.Append("    /// <summary>bit 번호 오름차순의 플래그 값. Names 와 첨자가 같다.</summary>\n");
        sb.Append("    public static readonly WorldFlags[] Values =\n    [\n");
        foreach (KeyValuePair<int, string> e in entries)
        {
            sb.Append("        WorldFlags.").Append(e.Value).Append(",\n");
        }

        sb.Append("    ];\n\n");

        sb.Append("    /// <summary>flag id 문자열 → 비트. 리플렉션을 쓰지 않는다.</summary>\n");
        sb.Append("    public static bool TryParse(string? id, out WorldFlags flag)\n    {\n");
        sb.Append("        switch (id)\n        {\n");
        foreach (KeyValuePair<int, string> e in entries)
        {
            sb.Append("            case \"").Append(e.Value).Append("\": flag = WorldFlags.")
              .Append(e.Value).Append("; return true;\n");
        }

        sb.Append("            default: flag = WorldFlags.None; return false;\n");
        sb.Append("        }\n    }\n\n");

        sb.Append("    /// <summary>비트마스크를 사람이 읽는 이름 목록으로. 예: \"AtHome|HasFood\".</summary>\n");
        sb.Append("    public static string Format(WorldFlags flags)\n    {\n");
        sb.Append("        if (flags == WorldFlags.None)\n        {\n");
        sb.Append("            return \"None\";\n        }\n\n");
        sb.Append("        var sb = new System.Text.StringBuilder();\n");
        sb.Append("        for (int i = 0; i < Values.Length; i++)\n        {\n");
        sb.Append("            if ((flags & Values[i]) == 0)\n            {\n");
        sb.Append("                continue;\n            }\n\n");
        sb.Append("            if (sb.Length > 0)\n            {\n");
        sb.Append("                sb.Append('|');\n            }\n\n");
        sb.Append("            sb.Append(Names[i]);\n        }\n\n");
        sb.Append("        return sb.ToString();\n    }\n");

        sb.Append("}\n");

        return sb.ToString();
    }
}
